name: GitHub Artifact
on:
    pull_request:
        types: [closed]
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: run test
              uses: npm run test
    build:
        runs-on: ubuntu-latest
        steps:
              name: checkout
              uses: actions/checkout@v4
              name: build
              uses: npm run build
              name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: build-artifact
                path: dist
    deploy:
        runs-on: ubuntu-latest
        needs: [build,test]
        steps:
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: build-artifact
                
            